MyOrange.Web/Pages/Customers/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyOrange.IServices;
using MyOrange.Models;

namespace MyOrange.Web.Pages.Customers
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public Customer Customer { get; set; }

        private readonly ICustomerService customerService;
        private readonly ICountryService countryService;
        private readonly IWebHostEnvironment webHostEnvironment;

        [BindProperty]
        public IFormFile Photo { get; set; }

        public SelectList Countries { get; set; }

        public CreateModel(ICustomerService customerService, ICountryService countryService, IWebHostEnvironment webHostEnvironment)
        {
            this.customerService = customerService;
            this.countryService = countryService;
            this.webHostEnvironment = webHostEnvironment;
        }

        public void OnGet()
        {
             Countries = new SelectList(countryService.Get());
            // niezłe
            // todo:

        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (Photo != null)
            {
                string file = Guid.NewGuid().ToString("N") + new FileInfo(Photo.FileName).Extension;
                var filename = Path.Combine(webHostEnvironment.WebRootPath, "uploads", file);
                using (var stream = new FileStream(filename, FileMode.Create))
                {
                    Photo.CopyTo(stream);
                }

                Customer.Photo = Path.Combine("/uploads", file);
            }

            customerService.Add(Customer);

            return RedirectToPage("Index");
        }
    }
}

MyOrange.Web/Pages/Customers/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyOrange.IServices;
using MyOrange.Models;

namespace MyOrange.Web.Pages.Customers
{
    public class DeleteModel : PageModel
    {
        [BindProperty]
        public Customer Customer { get; set; }

        private readonly ICustomerService customerService;

        public DeleteModel(ICustomerService customerService)
        {
            this.customerService = customerService;
        }

        public IActionResult OnGet(int id)
        {
            Customer = customerService.Get(id);

            if (Customer==null)
            {
                return RedirectToPage("/NotFound");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            customerService.Remove(Customer.Id);

            return RedirectToPage("Index");
        }
    }
}

MyOrange.Web/Pages/Customers/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyOrange.IServices;
using MyOrange.Models;
using Microsoft.AspNetCore.Http;

namespace MyOrange.Web.Pages.Customers
{
    public class DetailsModel : PageModel
    {
        private readonly ICustomerService customerService;

        public Customer Customer { get; set; }

        [BindProperty(SupportsGet = true)]
        public string Message { get; set; }
        
        [TempData]
        public string MessageTemp { get; set; }

        public string MessageSession { get; set; }

        public DetailsModel(ICustomerService customerService)
        {
            this.customerService = customerService;
        }

        public void OnGet(int id)
        {
            MessageSession = HttpContext.Session.GetString("key1");
            //HttpContext.Session.Remove("key1");
            //HttpContext.Session.Clear();

            Customer = customerService.Get(id);

            var message = TempData.Peek("MessageTemp");

            TempData.Keep("MessageTemp");
            TempData.Remove("MessageTemp");

            TempData.Keep();
            TempData.Clear();

        }
    }
}

MyOrange.Web/Pages/Customers/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyOrange.IServices;
using MyOrange.Models;

namespace MyOrange.Web.Pages.Customers
{
    public class EditModel : PageModel
    {
        private readonly ICustomerService customerService;
        private readonly ICountryService countryService;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EditModel(ICustomerService customerService, ICountryService countryService, IWebHostEnvironment webHostEnvironment)
        {
            this.customerService = customerService;
            this.countryService = countryService;
            this.webHostEnvironment = webHostEnvironment;
        }

        [BindProperty]
        public Customer Customer { get; set; }

        [BindProperty]
        public bool Notify { get; set; }

        [BindProperty]
        public IFormFile Photo { get; set; }
        public SelectList Countries { get; set; }

        public string Message { get; set; }


        [PageRemote(
            HttpMethod = "post", 
            PageHandler = "CheckEmail", 
            ErrorMessage = "Email Duplicated",
            AdditionalFields = "__RequestVerificationToken")]
        [BindProperty]
        public string Email { get; set; }


        // POST 
        public IActionResult OnPostCheckEmail()
        {
            var existing = new[] { "marcin.sulecki@gmail.com", "marcin.sulecki@akademia.altkom.pl", "marcin.sulecki@altkom.pl" };

            var valid = !existing.Contains(Email);

            return new JsonResult(valid);
        }

        public IActionResult OnGet(int id)
        {
            Countries = new SelectList(countryService.Get());

            Customer = customerService.Get(id);

            if (Customer == null)
            {
                return RedirectToPage("/NotFound");
            }

            return Page();

        }

        public IActionResult OnPostSavePreferences()
        {
            if (Notify)
            {
                Message = "You have turned on email notifications";
            }
            else
            {
                Message = "You have turned off email notifications";
            }

            return RedirectToPage("Details", new { id = Customer.Id, message = Message });
        }

        public IActionResult OnPostSavePreferencesTemp()
        {
            if (Notify)
            {
                Message = "You have turned on email notifications";
            }
            else
            {
                Message = "You have turned off email notifications";
            }

            TempData["message"] = Message;
            TempData["messagetemp"] = Message;

            HttpContext.Session.SetString("key1", Message);

            return RedirectToPage("Details", new { id = Customer.Id });
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            // string file = Path.GetFileName(Photo.FileName);

            if (Photo != null)
            {
                string file = Guid.NewGuid().ToString("N") + new FileInfo(Photo.FileName).Extension;
                var filename = Path.Combine(webHostEnvironment.WebRootPath, "uploads", file);
                using (var stream = new FileStream(filename, FileMode.Create))
                {
                    Photo.CopyTo(stream);
                }

                Customer.Photo = Path.Combine("/uploads", file);
            }


            customerService.Update(Customer);

            return RedirectToPage("./Index");

        }
    }
}

MyOrange.Web/Pages/Customers/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyOrange.IServices;
using MyOrange.Models;

namespace MyOrange.Web.Pages.Customers
{

    [BindProperties(SupportsGet = true)]
     // [Authorize(Roles = "Developer, Trainer")]
    public class IndexModel : PageModel
    {
        private readonly ICustomerService customerService;

        //[BindProperty(SupportsGet = true)]
        public string Country { get; set; }

        //[BindProperty(SupportsGet = true)]
        public string FirstName { get; set; }

        public IndexModel(ICustomerService customerService)
        {
            this.customerService = customerService;
        }

        public IList<Customer> Customers { get; set; }
      
        public void OnGet()
        {
            var roles = this.User.FindAll(ClaimTypes.Role);

            var mobilephone = this.User.FindFirstValue(ClaimTypes.MobilePhone);

            // smsService.Send(mobilephone, "Hello");

            if (string.IsNullOrEmpty(Country) && string.IsNullOrEmpty(FirstName))
            {
                Customers = customerService.Get();
            }
            else
            {
                Customers = customerService.Get(Country, FirstName);
            }

        }
    }
}

MyOrange.Web/ViewComponents/CustomerCardViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyOrange.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyOrange.Web.ViewComponents
{
    public class CustomerCardViewComponent : ViewComponent
    {


        public IViewComponentResult Invoke(Customer customer)
        {
            return View(customer);
        }
    }


}

MyOrange.Web/ViewComponents/DocumentsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyOrange.IServices;

namespace MyOrange.Web.ViewComponents
{
    public class DocumentsViewComponent : ViewComponent
    {
        private readonly IDocumentService documentService;

        public DocumentsViewComponent(IDocumentService documentService)
        {
            this.documentService = documentService;
        }

        public IViewComponentResult Invoke(int customerId)
        {
            var documents = documentService.Get(customerId);

            return View(documents);
        }
    }


}

MyOrange.Web/Pages/Customers/Create.cshtml
@page
@model MyOrange.Web.Pages.Customers.CreateModel
@{
    ViewData["Title"] = "Create";    
}

<h1>Create</h1>

<form method="post" enctype="multipart/form-data">

    <div class="form-row">
        <div class="form-group">
            <label asp-for="Customer.FirstName">First name</label>
            <input type="text" asp-for="Customer.FirstName" placeholder="First name" />
            <span asp-validation-for="Customer.FirstName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group">
            <label asp-for="Customer.LastName">Last name</label>
            <input type="text" asp-for="Customer.LastName" placeholder="Last name" />
            <span asp-validation-for="Customer.LastName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group">
            <label asp-for="Customer.Email">E-mail</label>
            <input type="email" asp-for="Customer.Email" placeholder="Email address" />
            <span asp-validation-for="Customer.Email" class="text-danger"></span>
        </div>
    </div>


    <div class="form-row">
        <div class="form-group">
            <label asp-for="Customer.Country">Country</label>
            <select class="form-control" asp-for="Customer.Country" asp-items="@Model.Countries">
                <option value="">Choose one</option>
            </select>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group">
            <label asp-for="Photo"></label>
            <input type="file" asp-for="Photo" class="form-control-file" />
        </div>
    </div>

    <button type="submit" class="btn btn-success btn-block">Save</button>
    <a class="btn btn-primary btn-block" asp-page="Index">Cancel</a>

    @*@section Scripts {
        <partial name="_ValidationScriptsPartial" />
    }*@

</form>

MyOrange.Web/Pages/Customers/Delete.cshtml
@page "{id}"
@model MyOrange.Web.Pages.Customers.DeleteModel
@{
    ViewData["Title"] = "Delete";
}

<partial name="_CustomerViewPartial" model="@Model.Customer" view-data="ViewData" />


<div class="alert alert-danger">
    <h5>Are you sure delete customer @Model.Customer.FirstName @Model.Customer.LastName ?</h5>

    <form method="post">
        <button type="submit" class="btn btn-danger btn-block">Yes</button> 
        <a class="btn btn-primary btn-block" asp-page="/Customers/Index">No</a>
    </form>

</div>

MyOrange.Web/Pages/Customers/Details.cshtml
@page "/Customers/View/{id:range(1, 100)}"
@model MyOrange.Web.Pages.Customers.DetailsModel
@{
    ViewData["Title"] = "Customer Details";
}

<h1>Customer Details</h1>

@*<h2>Customer Id @Request.Query["id"] </h2>*@

<partial name="_CustomerViewPartial" model="@Model.Customer" view-data="ViewData" />

<customer-card customer="@Model.Customer"></customer-card>

@await Component.InvokeAsync("CustomerCard", Model.Customer)

<vc:customer-card customer="@Model.Customer"></vc:customer-card>


@if (!string.IsNullOrEmpty(Model.Message))
{
    <div class="alert alert-primary">
        @Model.Message
    </div>
}

@if (TempData["message"] != null)
{
    <div class="alert alert-dark">
        @TempData["message"]
    </div>
}

@if (Model.MessageTemp != null)
{
    <div class="alert alert-info">
        @Model.MessageTemp
    </div>
}

@if (Model.MessageSession != null)
{
    <div class="alert alert-success">
        @Model.MessageSession
    </div>
}


<div>
    <a class="btn btn-primary" asp-page="/Customers/Index">Back to Customers</a>
</div>

MyOrange.Web/Pages/Customers/Edit.cshtml
@page "{id:min(1)}/{handler?}"
@model MyOrange.Web.Pages.Customers.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<form method="post" asp-page-handler="SavePreferences">
    <div class="form-check">
        <input id="notify" type="checkbox" asp-for="Notify" class="form-check-input" />
        <label for="notify" class="form-check-label">Send email</label>
    </div>

    <button type="submit" class="btn btn-primary btn-block">Save Preferences</button>
</form>

<div class="alert alert-primary">
    @Model.Message
</div>

<form method="post" asp-page-handler="SavePreferencesTemp">
    <div class="form-check">
        <input id="notifytemp" type="checkbox" asp-for="Notify" class="form-check-input" />
        <label for="notifytemp" class="form-check-label">Send email</label>
    </div>

    <button type="submit" class="btn btn-primary btn-block">Save Preferences Temp</button>
</form>


<div>
    <form method="post" enctype="multipart/form-data" asp-page-handler="OnPost">

        <input type="hidden" asp-for="Customer.Id" />
        <input type="hidden" asp-for="Customer.Photo" />
        <input type="hidden" asp-for="Customer.RowVersion" />

        <div class="form-row">
            <div class="form-group">
                <label asp-for="Customer.FirstName">First name</label>
                <input type="text" asp-for="Customer.FirstName" placeholder="First name" />
                <span asp-validation-for="Customer.FirstName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group">
                <label asp-for="Customer.LastName">Last name</label>
                <input type="text" asp-for="Customer.LastName" placeholder="Last name" />
                <span asp-validation-for="Customer.LastName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group">
                <label asp-for="Customer.Email">E-mail</label>
                <input type="email" asp-for="Customer.Email" placeholder="Email address" />
                <span asp-validation-for="Customer.Email" class="text-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group">
                <label asp-for="Email">Remote E-mail</label>
                <input type="email" asp-for="Email" placeholder="Email address" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group">
                <label asp-for="Customer.Country">Country</label>
                <select class="form-control" asp-for="Customer.Country" asp-items="Model.Countries">
                    <option value="">Choose one</option>
                </select>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group">
                <label asp-for="Photo"></label>
                <input type="file" asp-for="Photo" class="form-control-file" />
            </div>
        </div>

        <button type="submit" class="btn btn-success btn-block">Save</button>
        <a class="btn btn-primary btn-block" asp-page="Index">Cancel</a>

        @section Scripts {
            <partial name="_ValidationScriptsPartial" />
        }

    </form>

    <img src="@Model.Customer.Photo" />


</div>

MyOrange.Web/Pages/Customers/Index.cshtml
@page
@model MyOrange.Web.Pages.Customers.IndexModel
@{
    ViewData["Title"] = "Customers";
}

<h1>Customers</h1>

<!-- Page Header -->

<div>
    <a asp-page="./Create" class="btn btn-primary">Add Customer</a>
</div>

@if (User.IsInRole("Developer"))
{
}

<!-- Panel search -->
<form method="get">
    <div class="input-group">
        <input type="text" class="form-control" asp-for="FirstName" placeholder="First name" />
        <input type="text" class="form-control" asp-for="Country" placeholder="Country" />
        <div>
            <button class="btn btn-primary" type="submit">
                <i class="fas fa-search fa-sm" aria-hidden="true"></i>
            </button>
            <a asp-route-firstname="" asp-route-country="" class="btn btn-primary">Clear</a>
        </div>
    </div>
</form>



<!-- Customers -->
<table class="table table-hover table-light table-striped">
    <thead>
        <tr>
            <th scope="col">@Html.DisplayNameFor(m => m.Customers[0].Id)</th>
            <th scope="col">@Html.DisplayNameFor(m => m.Customers[0].FirstName)</th>
            <th scope="col">@Html.DisplayNameFor(m => m.Customers[0].LastName)</th>
            <th scope="col">@Html.DisplayNameFor(m => m.Customers[0].Email)</th>
            <th scope="col">@Html.DisplayNameFor(m => m.Customers[0].Country)</th>
            <th scope="col">@Html.DisplayNameFor(m => m.Customers[0].IsRemoved)</th>
        </tr>
    </thead>

    <tbody>

        @foreach (var customer in Model.Customers)
        {
            <tr>
                <td>@Html.DisplayFor(m => customer.Id)</td>
                <td>@Html.DisplayFor(m => customer.FirstName)</td>
                <td>@Html.DisplayFor(m => customer.LastName)</td>
                <td>@Html.DisplayFor(m => customer.Email)</td>
                <td>@Html.DisplayFor(m => customer.Country)</td>
                <td>@Html.DisplayFor(m => customer.IsRemoved)</td>

                <td>
                    <a class="btn btn-primary" asp-page="./Details" asp-route-id="@customer.Id">View</a>
                    <a class="btn btn-primary" asp-page="./Edit" asp-route-id="@customer.Id">Edit</a>
                    <a class="btn btn-danger" asp-page="./Delete" asp-route-id="@customer.Id">Delete</a>
                    <a class="btn btn-success" data-toggle="modal" data-target="#myModal">Popup</a>
                </td>

            </tr>
        }

    </tbody>
</table>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Content -->
        <div class="modal-content">
            <div class="modal-header">Header </div>
            <div class="modal-body">                
                @*<partial name="Details" />*@

                @*<vc:documents customer-id="1" ></vc:documents>*@
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Ok</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>

</div>