MyOrange.Web/Pages/Dashboard.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MyOrange.IServices;

namespace MyOrange.Web.Pages
{
    public class DashboardModel : PageModel
    {
        private readonly ICustomerService customerService;
        private readonly IDocumentService documentService;

        [BindProperty]
        public int ActiveCustomersCount { get; private set; }

        [BindProperty]
        public int DocumentsCount { get; private set; }

        public DashboardModel(ICustomerService customerService, IDocumentService documentService)
        {
            this.customerService = customerService;
            this.documentService = documentService;
        }

        public void OnGet()
        {
            ActiveCustomersCount = customerService.GetActive();
            DocumentsCount = documentService.GetCount();

        }

        public void OnGetGenerate()
        {

        }

        public void OnGetAction()
        {

        }

        public void OnGetAnotherAction()
        {

        }

        public void OnGetSomethingElseAction()
        {

        }
    }
}

MyOrange.Web/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MyOrange.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MyOrange.Web/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MyOrange.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            _logger.LogInformation("You requested the Index page");
        }
    }
}

MyOrange.Web/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace MyOrange.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MyOrange.Web/ViewComponents/ProgressBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyOrange.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyOrange.Web.ViewComponents
{
    public class ProgressBarViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string title, int value)
        {
            return View(new Project { Title = title , Value = value });
        }
    }
}

MyOrange.Web/Pages/Dashboard.cshtml
@page
@model MyOrange.Web.Pages.DashboardModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@



<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    <a asp-page-handler="Generate" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
</div>


<!-- Content Row -->
<div class="row">

    <!-- Customers Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Active Customers</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">@Model.ActiveCustomersCount</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-users fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Earnings (Annual)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">100</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Task Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Tasks</div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">10%</div>
                            </div>
                            <div class="col">
                                <div class="progress progress-sm mr-2">
                                    <div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Pending Documents</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">@Model.DocumentsCount</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-folder fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


<!-- Content Row -->

<div class="row">
    <!-- Area Chart -->
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Projects</h6>

                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink" x-placement="bottom-end" style="position: absolute; transform: translate3d(-156px, 19px, 0px); top: 0px; left: 0px; will-change: transform;">
                        <div class="dropdown-header">Dropdown Header:</div>
                        <a class="dropdown-item" asp-page-handler="Action">Action</a>
                        <a class="dropdown-item" asp-page-handler="AnotherAction">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-page-handler="SomethingElseAction">Something else here</a>
                    </div>
                </div>

            </div>
            <!-- Card Body -->
            <div class="card-body">
                @*@await Component.InvokeAsync("ProgressBar", new { title = "Server Migration", value = 20 })*@

                <vc:progress-bar title="Server Migration" value="20"></vc:progress-bar>

                <progress-bar title="Sales Tracking" value="40"></progress-bar>
                <progress-bar title="Customer Database" value="60"></progress-bar>
                <progress-bar title="Payout Details" value="80"></progress-bar>
                <progress-bar title="Account Setup" value="100"></progress-bar>

            </div>
        </div>
    </div>
  
</div>

MyOrange.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome .NET Core</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <current-time></current-time>

</div>

MyOrange.Web/Pages/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}



<div class="text-center">
    <div class="error mx-auto">404</div>
    <p class="lead text-gray-800 mb-5">Page Not Found</p>

    <a asp-page="/Customers/Index">Back to Customers</a>
</div>

MyOrange.Web/Pages/Users.cshtml
@page "usersx"
@{
    ViewData["Title"] = "Users";
}

<h1>Users</h1>